"""empty message

Revision ID: 2fb62e70b1f4
Revises: 
Create Date: 2020-11-07 18:35:41.270459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb62e70b1f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('_zipcode', sa.String(length=128), nullable=True),
    sa.Column('_address', sa.String(length=128), nullable=True),
    sa.Column('_country', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_transaction_id')
    )
    op.create_table('transaction_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_quantity', sa.Integer(), nullable=True),
    sa.Column('_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('_product_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['_product_id'], ['product._product_id'], ),
    sa.ForeignKeyConstraint(['_transaction_id'], ['transaction._transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_item')
    op.drop_table('transaction')
    # ### end Alembic commands ###
